spring:
  application:
      name: "VK User Membership Service"
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100000,expireAfterWrite=15m

vk:
  api:
    base-url: https://api.vk.com
    version: 5.199
    endpoints:
      users-get: /method/users.get
      groups-is-member: /method/groups.isMember

logging:
  level:
    org:
      apache:
        camel:
          component: DEBUG
