---
apiVersion: v1
kind: Service
metadata:
  name: vk-user-membership-service
  labels:
    app: vk-user-membership-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vk-user-membership-service